### ISSUE TITLE
how could I get this feature with opentelemetry-javaagent

### ISSUE THREAD

**Issue by goodLuckForWorld** [DGuhr/spring-otel-extended#1]
Hi @DGuhr 
The extension you developed is fantastic. It's what I need, I use commands“ Java - opentelemetry-javaagent. jar - jar app. jar” to obtain trace. How can I put the extension you developed into opentelemetry-javaagent. jar? Which version of opentelemetry-javaagent. jar do I need? Looking forward to your reply. Thank you

**Comment by DGuhr** [comment]
Hi @goodLuckForWorld - I'm more than happy that you like it! :)

You can find a working command, adding the extension jar to opentelemetry agent (1.32.0 and 1.33.0 are the versions I tested) here in the code:
https://github.com/DGuhr/spring-otel-extended/blob/88d9a90ad06b874e61b5069e258e788c7a250a43/extension-based-otel-animal-app/Dockerfile#L17
so it's basically 
`java -javaagent:opentelemetry-javaagent.jar -Dotel.javaagent.extensions=spring-extension.jar -jar yourApp.jar`

You can use the [extension jar file](https://github.com/DGuhr/spring-otel-extended/tree/main/extension-based-otel-animal-app/agent) from this repository (built using JDK 21 if I remember correctly) or build it yourself, by forking/cloning the project locally and then navigating to the [otel-javaagent-extension folder](https://github.com/DGuhr/spring-otel-extended/tree/main/otel-javaagent-spring-extension) and running `mvn clean package` in that folder (Assuming you have maven installed here) - it'll appear in the `target` folder, then. 

**Important**: **The extension only works when it was built with the same JDK that is used at runtime.** So, at buildtime, or in other words when you build the extension from the folder I mention above using maven, make sure you use the same Java JDK version (11,17,21,...) your app is running on while building it (run `java --version` when in doubt). 

I hope this helps you to get started! I leave this open a bit, so you can confirm it works.

Regards,
Dominik
 
p.s. Please don't use it in production, unless you know what you're doing. This is an experimental extension and it creates a lot more spans per trace than the auto-instrumentation does. This could severely increase your cost for storing the traces (if you do not use OSS but SaaS vendors, it depends on the pricing calculations used).

**Comment by goodLuckForWorld** [comment]
Thank you for your reply. Trace can now retrieve the method name from the service, which is great. My app uses ibatis to access the database, and the corresponding class uses "org.apache.ibatis.annotations.Mapper" annotation, how can I track this class in trace? I modified the source code to 
```
    public ElementMatcher<TypeDescription> typeMatcher() {
        logger.info("TEST typeMatcher");
        return isAnnotatedWith(named("org.springframework.stereotype.Service"))
                .or(isAnnotatedWith(named("org.springframework.stereotype.Component")))
                .or(isAnnotatedWith(named("org.springframework.stereotype.Repository")))
                .or(isAnnotatedWith(named("org.apache.ibatis.annotations.Mapper")));
    }
```
, but it seems to have no effect

**Comment by DGuhr** [comment]
That's great to hear, first of all. 

For your follow-up problem: To be honest, I would've done the same - add the annotation, rebuild the extension and then it'd work, usually. 

One thing comes to my mind: Maybe the annotated method is not public?

The extension currently only checks public methods, see this line here:
https://github.com/DGuhr/spring-otel-extended/blob/88d9a90ad06b874e61b5069e258e788c7a250a43/otel-javaagent-spring-extension/src/main/java/org/acme/SpringExtendedInstrumentation.java#L39

So either you change your method signature to public (which is not really a healthy thing to do if there's no need otherwise), or you change the transform method to also include other methods, e.g. like this: `typeTransformer.applyAdviceToMethod(isPublic().or(isProtected()).and(isMethod()), this.getClass().getName()+"$SpringBeanAdvice");` to also add protected methods. I did not try this yet, tbh.

If that does not work, maybe you could ask at the ibatis / mybatis repositories for further advice. 

Hope this helps.
